'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tummo_Writer_Pro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property About_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property accept_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property agt_action_success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agt_action_success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_addresses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_addresses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bookmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bookmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bookmark_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bookmark_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property books_infront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("books_infront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check_box_mix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_box_mix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check_box_uncheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_box_uncheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_copies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_copies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_editing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_editing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_insert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_insert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_view_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_view_book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_extension_doc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_extension_doc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filter_advanced() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_advanced", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_explorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_explorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grouping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grouping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_page_icon__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home-page-icon (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property insert_element() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insert_element", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_folder1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_folder1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property photo_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("photo_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property photos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("photos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property project() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("project", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;project&gt;
        '''  &lt;root id=&quot;0&quot; tittle=&quot;Tittle Documents&quot; author=&quot;Author Documents&quot; cover=&quot;picture.png&quot; /&gt;
        '''  &lt;folder id=&quot;1&quot; tittle=&quot;New Documents&quot; /&gt;
        '''  &lt;document folderid=&quot;1&quot; id=&quot;3&quot; tittle=&quot;Chapter 1&quot; file=&quot;1.docx&quot; /&gt; 
        '''  &lt;document folderid=&quot;1&quot; id=&quot;5&quot; tittle=&quot;Chapter 3&quot; file=&quot;2.docx&quot; /&gt;
        '''  &lt;folder id=&quot;2&quot; tittle=&quot;Notes&quot; /&gt;
        '''  &lt;document folderid=&quot;2&quot; id=&quot;6&quot; tittle=&quot;Note 1&quot; file=&quot;3.docx&quot; /&gt;
        '''  &lt;document folderid=&quot;2&quot; id=&quot;7&quot; tittle=&quot;Note 2&quot; file=&quot;4.docx&quot; /&gt;  
        '''&lt;/project&gt;.
        '''</summary>
        Friend ReadOnly Property project_tummo() As String
            Get
                Return ResourceManager.GetString("project.tummo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property property_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("property_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property run_macros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run_macros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property server_configuration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_configuration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sort_asc_az() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sort_asc_az", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tab_content() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_content", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property table_excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;project&gt;
        '''  &lt;root id=&quot;0&quot; tittle=&quot;Tittle Documents&quot; author=&quot;Author Documents&quot; cover=&quot;picture.png&quot; /&gt;
        '''  &lt;folder id=&quot;1&quot; tittle=&quot;New Documents&quot; /&gt;
        '''  &lt;document folderid=&quot;1&quot; id=&quot;3&quot; tittle=&quot;Chapter 1&quot; file=&quot;1.docx&quot; /&gt; 
        '''  &lt;document folderid=&quot;1&quot; id=&quot;5&quot; tittle=&quot;Chapter 3&quot; file=&quot;2.docx&quot; /&gt;
        '''  &lt;folder id=&quot;2&quot; tittle=&quot;Notes&quot; /&gt;
        '''  &lt;document folderid=&quot;2&quot; id=&quot;6&quot; tittle=&quot;Note 1&quot; file=&quot;3.docx&quot; /&gt;
        '''  &lt;document folderid=&quot;2&quot; id=&quot;7&quot; tittle=&quot;Note 2&quot; file=&quot;4.docx&quot; /&gt;  
        '''&lt;/project&gt;.
        '''</summary>
        Friend ReadOnly Property template1() As String
            Get
                Return ResourceManager.GetString("template1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tree_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tree_list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1|Dự án mới
        '''2|Mở
        '''3|Lưu
        '''4|Đóng.
        '''</summary>
        Friend ReadOnly Property vietnamese() As String
            Get
                Return ResourceManager.GetString("vietnamese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property viewstack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewstack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YouTube_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YouTube-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
